### ISSUE TITLE
Mobilna wygląda dziwnie

### ISSUE THREAD

**Issue by mbalc** [annkamsk/polishlyrics#4]
Screenshot [android, Samsung a52s, przeglądarka Vivaldi]
![Screenshot_20230106_202617_Vivaldi Browser](https://user-images.githubusercontent.com/11033790/211085200-771ade01-b3f0-48ce-b47f-9a2f8e4ae85a.jpg)

- Podwójny hamburger button
- za duży margin/padding -> bardzo krotkie linijki 
(Tytuł issuesa miał być "mobilka", ale autokorekta)

**Comment by annkamsk** [comment]
Usunęłam drugie i trzecie menu + dałam custom menu dla mobile. Powinno wyglądać lepiej. To wordpress z jakimś custom builderem, więc to tyle co mogę zrobić bez wchodzenia w CSS-a
<img width="468" alt="image" src="https://user-images.githubusercontent.com/37103414/211093353-941fe5d9-71df-4773-b194-4ce36362ac83.png">

**Comment by mbalc** [comment]
Wygląda ok
Here's an auto-dark theme view btw
![Screenshot_20230108_115814_Vivaldi Browser](https://user-images.githubusercontent.com/11033790/211192404-93c011c8-bb1c-4fd6-8ef5-835a569978c1.png)
