### ISSUE TITLE
Before day begins thread

### ISSUE THREAD

**Issue by annkamsk** [annkamsk/polishlyrics#9]
* L45: czy "shake their heads" jest tak samo intuicyjnie rozumiane po angielsku jako "kręcenie głową z dezaprobatą"
* "but not now" można by zamienić na "not today" pod warunkiem poprawienia "dusk will come", aby utrzymać rym

**Comment by annkamsk** [comment]
>Where fruit have rotten black

@k3rnelj mam tu wątpliwość. 1. w tym kontekście fruit jest raczej countable, więc "fruits" 2. a jeśli uncountable, to chyba "fruit has". Nie znajduję nigdzie użycia "fruit" + plural verb form

**Comment by k3rnelj** [comment]
> > Where fruit have rotten black
> 
> @k3rnelj mam tu wątpliwość. 1. w tym kontekście fruit jest raczej countable, więc "fruits" 2. a jeśli uncountable, to chyba "fruit has". Nie znajduję nigdzie użycia "fruit" + plural verb form

Siedzimy na githubie, to dam odpowiedź ze stacka: https://english.stackexchange.com/a/58138
(tbh po prostu jest dobrze wyjaśniona)
i tu mamy sytuację z ostatniego bulletpointa - żeby pójść do _fruits_ musielibyśmy chieć wyróżnić podklasy tych owoców.

A poza rozkminą gramatyczną, która admittedly jest na wątłym gruncie, bo ludzie po prostu różnie tego używają i ciężko o konsensus, to skorzystałbym z tej ambiwalencji i zostałbym przy _fruit_ na rzecz tego, żeby nie musieć przy śpiewaniu artykułować _tsh_ tam gdzie teraz mamy czyste niesyczące 'th'

**Comment by k3rnelj** [comment]
TLDR obie wersje da się obronić gramatycznie więc proponuję zostanie przy _fruit_ na rzecz łatwiejszego śpiewania (i nagrania). Błędu nie popełniamy, w porywach pozwalamy sobie na nieścisłość

**Comment by annkamsk** [comment]
Zgadzam się, że obie opcje okej i że lepiej dać "fruit" dla wymowy, ale moja jedyna wątpliwość, to czy jeśli używamy "fruit", to czy nie powinno być "fruit has"? Skoro to sytuacja z ostatniego bullet pointa, to używamy wersji uncountable, która ma chyba taki sam styl odmiany jak forma pojedyncza. 
Pod linkiem, który wkleiłeś jest przykład z użyciem "fruit are"
>Many fruit from the genus Vaccinium are rich in phytonutrients, including those with potent antioxidant properties.

ale to ten countable przykład z ostatniego bulletpointu: "but they take a countable sense when we talk about different varieties". 
Ale eh, masz rację, że to co najwyżej nieścisłość, a łatwiej śpiewać z "have"

**Comment by k3rnelj** [comment]
Aaa, to taka była wątpliwość, a to jeszcze prościej - _fruit_ jest legalną formą mnogą _fruit_ (według co niektórych ekstremistów nawet jedyną) - i w związku z tym legalnie możemy zrobić _fruit have_

**Comment by mbalc** [comment]
chyba do zamkniecia juz
